#!/bin/bash 
#
# rundeckd    Startup script for the rundeck
#
# chkconfig: 2345 90 10
# description: rundeckd, providing rundeckd
# pidfile: /var/run/rundeckd.pid

# Source function library
. /etc/rc.d/init.d/functions
. /etc/rundeck/profile

prog="rundeckd"
rundeckd="${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"
RETVAL=0
PID_FILE=/var/run/${prog}.pid
servicelog=/var/log/rundeck/service.log

start() {
	echo -n $"Starting $prog: "
	if ! touch $servicelog; then
		echo No access to $servicelog. This usually means you need to be root
		echo_failure
		echo
		return 1
	fi
        nohup runuser -s /bin/bash -l rundeck -c "$rundeckd" >>$servicelog 2>&1 &
 	RETVAL=$?	
	PID=$!
	echo $PID > $PID_FILE
	if [ $RETVAL -eq 0 ]; then 
		touch /var/lock/subsys/$prog
		echo_success
	else
		echo_failure
	fi
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE "$rundeckd"
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

### NOT USED
reload() {
	echo -n $"Reloading $prog: "
	killproc -p $PID_FILE "$rundeckd" -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ]; then
			stop
			start
		fi
		;;
	status)
		status -p $PID_FILE $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|condrestart|status}"
		RETVAL=1
esac

exit $RETVAL
