package com.dtolabs.rundeck.core.audit;


import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Describes an audit event generated by the system.
 *
 */
public interface AuditEvent extends Serializable {

  /**
   * @return Timestamp of the event.
   */
  Date getTimestamp();

  /**
   * Gets the username
   *
   * @return
   */
  String getUsername();

  /**
   * The roles associated with the user
   *
   * @return
   */
  List<String> getUserRoles();

  /**
   * The type of the event, as described by {@link Action}
   *
   * @return Event type.
   */
  Action getAction();

  /**
   * @return Type of the resource that generated the event. Null if does not apply.
   */
  ResourceType getResourceType();


  /**
   * @return Name or ID of the resource that generated the event. Null if does not apply.
   */
  String getResourceName();


  /**
   * The type of resource associated with the event.
   */
  enum ResourceType {
    project,
    user
  }


  /**
   * The kind of action that triggered an event.
   */
  enum Action {
    login_success,
    login_failed,
    logout,
    view
  }



}
