package com.dtolabs.rundeck.core.audit;


import com.dtolabs.rundeck.core.common.Framework;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Describes an audit event generated by the system.
 *
 */
public interface AuditEvent extends Serializable {

  /**
   * @return Timestamp of the event.
   */
  Date getTimestamp();

  /**
   * Gets the username
   *
   * @return
   */
  String getUsername();

  /**
   * The roles associated with the user
   *
   * @return
   */
  List<String> getUserRoles();

  /**
   * The type of action that generated the event.
   *
   * @see Action
   * @return Event type.
   */
  Action getAction();

  /**
   * @return Type of the resource that generated the event. Null if does not apply.
   */
  ResourceType getResourceType();


  /**
   * @return Name or ID of the resource that generated the event. Null if does not apply.
   */
  String getResourceName();


  /**
   * The type of resource associated with the event.
   */
  enum ResourceType {
    user,
    project
  }


  /**
   * Types of actions that generate audit events.
   */
  enum Action {
    login_success,
    login_failed,
    logout,
    view
  }



}
