databaseChangeLog = {
    changeSet(author: "rundeckuser (generated)", id: "1646926526113", dbms: "h2") {
        comment { 'Alter columns with id to auto increment by default' }
        grailsChange {
            change {
                sql.execute("alter table AUTH_TOKEN alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table BASE_REPORT alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table EXECUTION alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table JOB_FILE_RECORD alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table LOG_FILE_STORAGE_REQUEST alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table NODE_FILTER alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table NOTIFICATION alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table ORCHESTRATOR alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table PLUGIN_META alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table PROJECT alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table RDOPTION alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table RDUSER alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table REFERENCED_EXECUTION alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table REPORT_FILTER alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table SCHEDULED_EXECUTION alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table SCHEDULED_EXECUTION_FILTER alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table SCHEDULED_EXECUTION_STATS alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table STORED_EVENT alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table STORAGE alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table WEBHOOK alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table WORKFLOW alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
                sql.execute("alter table WORKFLOW_STEP alter column id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL;")
            }
            rollback {
            }
        }
    }
}