/*
 * Copyright 2026 SimplifyOps Inc, <http://simplifyops.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.rundeck.util

import groovy.transform.CompileStatic
import org.owasp.html.HtmlSanitizer

import java.util.regex.Matcher
import java.util.regex.Pattern

/**
 * Converts hand-written HTML {@code <table>} blocks found inside raw job
 * description text into an equivalent GFM (GitHub Flavored Markdown) pipe
 * table, so that it can be rendered by the existing, unmodified
 * {@code rundeck.codecs.MarkdownCodec} -&gt; {@code rundeck.codecs.SanitizedHTMLCodec}
 * pipeline exactly as if the user had typed Markdown table syntax themselves.
 * <p>
 * {@code MarkdownCodec} deliberately escapes raw inline/block HTML as text
 * rather than rendering it live, to prevent attacker-controlled HTML/CSS
 * from reaching the sanitizer as executable markup. This class is kept
 * intentionally isolated from both codecs so that guarantee is never
 * weakened: it extracts only the plain text content of each table cell --
 * discarding every tag and attribute entirely -- and rebuilds a Markdown
 * pipe table from that text. No user-authored tag or attribute is ever
 * copied into the output; only plain text wrapped in Markdown syntax
 * generated by this class. It is meant to be called as a pre-processing
 * step on raw description text, before that text is handed to
 * {@code <g:markdown>}.
 * <p>
 * Finding the boundaries of a {@code <table>} block, and the row/cell
 * structure inside it, is deliberately NOT done with ad-hoc regular
 * expressions: a regex cannot soundly track "am I inside a quoted attribute
 * value" across an entire document, and an asymmetry between how open tags,
 * close tags, and tag-counting handled quotes previously let an attacker
 * hide a fake closing tag inside a quoted attribute to truncate a match
 * early and smuggle live Markdown past this class entirely. Table
 * boundaries are instead found with a small, single-pass, quote-aware
 * scanner ({@link #findTopLevelTables}), and row/cell text is extracted by
 * feeding each correctly-bounded table through the OWASP HTML Sanitizer's
 * public streaming tokenizer ({@link HtmlSanitizer#sanitize}) -- the same
 * library and the same trust boundary {@code SanitizedHTMLCodec} already
 * relies on -- via a {@link TableExtractionPolicy} that never reads or
 * copies tag attributes anywhere.
 */
@CompileStatic
class HtmlTableToMarkdownConverter {

    private static final Pattern FENCED_CODE_BLOCK = Pattern.compile(
        '^[ ]{0,3}(`{3,}|~{3,})[^\\n]*\\n.*?^[ ]{0,3}\\1[ \\t]*$',
        Pattern.MULTILINE | Pattern.DOTALL
    )
    private static final Pattern INLINE_CODE_SPAN = Pattern.compile('(`+).*?\\1')
    private static final Pattern WHITESPACE_RUN = Pattern.compile('\\s+')

    /**
     * Holds the extracted plain-text cells of a single {@code <tr>} row, and
     * whether the row used {@code <th>} cells (i.e. is a header row).
     */
    private static class RowData {
        boolean header
        List<String> cells = []
    }

    /**
     * The character range of one top-level {@code <table>...</table>} block
     * in the original text, as found by {@link #findTopLevelTables}.
     */
    private static class TableSpan {
        int start
        int end
        boolean nested
    }

    /**
     * Pre-processes raw description text: detects well-formed HTML
     * {@code <table>} blocks and replaces each one, in place, with an
     * equivalent GFM Markdown pipe table built only from the plain-text
     * content of each cell. Text outside of {@code <table>} blocks -- and
     * any other raw HTML tag -- is left completely untouched. A
     * {@code <table>} written inside a Markdown fenced code block or inline
     * code span is treated as a documented example, not live HTML, and is
     * never converted.
     * <p>
     * Fails safe: if the input contains unbalanced or nested {@code <table>}
     * tags, or any table cannot be meaningfully parsed into rows/cells, the
     * original text is returned unchanged rather than throwing or emitting
     * partial output.
     *
     * @param text raw description text, possibly containing hand-written HTML tables
     * @return text with any detected HTML tables replaced by Markdown tables,
     *         or the original text unchanged if nothing was converted or a
     *         parse problem was detected
     */
    static String convert(String text) {
        if (!text) {
            return text
        }
        try {
            return replaceTables(text)
        } catch (Exception ignored) {
            // Fail safe: never throw, never emit partial output.
            return text
        }
    }

    private static String replaceTables(String text) {
        List<TableSpan> spans = findTopLevelTables(text)
        if (spans.isEmpty()) {
            return text
        }
        List<int[]> codeRanges = findCodeRanges(text)
        StringBuilder result = new StringBuilder()
        int lastEnd = 0
        boolean convertedAny = false
        for (TableSpan span : spans) {
            if (span.nested) {
                // A <table> nested inside another <table> is not supported
                // -- fail safe for the whole text rather than risk an
                // incomplete or confusing partial conversion.
                return text
            }
            if (overlapsAnyRange(span.start, span.end, codeRanges)) {
                // A <table> written inside a fenced code block or inline
                // code span is a documented example, not live HTML -- leave
                // it exactly as authored.
                continue
            }
            String markdownTable = buildMarkdownTable(text.substring(span.start, span.end))
            if (markdownTable == null) {
                // A detected table could not be parsed into a meaningful
                // structure -- fail safe for the whole text rather than
                // emit a partially-converted result.
                return text
            }
            result.append(text, lastEnd, span.start)
            result.append('\n\n').append(markdownTable).append('\n\n')
            lastEnd = span.end
            convertedAny = true
        }
        if (!convertedAny) {
            return text
        }
        result.append(text, lastEnd, text.length())
        return result.toString()
    }

    /**
     * Single-pass, quote-aware scan for top-level {@code <table>...</table>}
     * blocks. A quoted attribute value (single- or double-quoted) is skipped
     * as one unit when looking for a tag's closing {@code >}, so a
     * {@code >} -- or a fake {@code </table>} -- hidden inside one can never
     * be mistaken for real markup. A table is marked {@code nested} if
     * another {@code <table>} opens before its matching close is found.
     */
    private static List<TableSpan> findTopLevelTables(String text) {
        List<TableSpan> spans = []
        int length = text.length()
        int i = 0
        int depth = 0
        int currentStart = -1
        boolean nestedSeen = false
        while (i < length) {
            char c = text.charAt(i)
            if (c != '<' as char) {
                i++
                continue
            }
            boolean isOpenTable = isTagNamed(text, i, 'table', false)
            boolean isCloseTable = isTagNamed(text, i, 'table', true)
            int tagEnd = skipTag(text, i)
            if (tagEnd < 0) {
                // Unterminated tag: stop scanning, nothing further can be
                // trusted as a complete table.
                break
            }
            if (isOpenTable) {
                if (depth == 0) {
                    currentStart = i
                    nestedSeen = false
                } else {
                    nestedSeen = true
                }
                depth++
            } else if (isCloseTable && depth > 0) {
                depth--
                if (depth == 0) {
                    spans << new TableSpan(start: currentStart, end: tagEnd, nested: nestedSeen)
                }
            }
            i = tagEnd
        }
        return spans
    }

    /**
     * Given the index of a {@code <} character, returns the index just past
     * the tag's matching, quote-aware {@code >} -- a {@code >} inside a
     * single- or double-quoted attribute value does not end the tag.
     * Returns -1 if the tag is never closed (truncated/malformed input).
     */
    private static final char NO_QUOTE = (char) 0

    private static int skipTag(String text, int ltIndex) {
        int length = text.length()
        int i = ltIndex + 1
        char quote = NO_QUOTE
        while (i < length) {
            char c = text.charAt(i)
            if (quote != NO_QUOTE) {
                if (c == quote) {
                    quote = NO_QUOTE
                }
            } else if (c == '"' as char || c == '\'' as char) {
                quote = c
            } else if (c == '>' as char) {
                return i + 1
            }
            i++
        }
        return -1
    }

    /**
     * Whether the tag starting at {@code ltIndex} (a {@code <} character) is
     * specifically an open (or, if {@code closing}, a close) tag for
     * {@code name}, case-insensitively, as opposed to some other tag whose
     * name happens to start with the same letters (e.g. {@code <tablecloth>}).
     */
    private static boolean isTagNamed(String text, int ltIndex, String name, boolean closing) {
        int length = text.length()
        int i = ltIndex + 1
        if (closing) {
            if (i >= length || text.charAt(i) != '/' as char) {
                return false
            }
            i++
        }
        if (!text.regionMatches(true, i, name, 0, name.length())) {
            return false
        }
        int after = i + name.length()
        if (after >= length) {
            return true
        }
        char next = text.charAt(after)
        return Character.isWhitespace(next) || next == '>' as char || next == '/' as char
    }

    /**
     * Finds the character ranges of Markdown fenced code blocks and inline
     * code spans in {@code text}, so {@link #replaceTables} can skip any
     * {@code <table>} found inside them -- those are documented examples,
     * not raw HTML meant to be rendered live.
     */
    private static List<int[]> findCodeRanges(String text) {
        List<int[]> ranges = []
        addMatchRanges(FENCED_CODE_BLOCK, text, ranges)
        addMatchRanges(INLINE_CODE_SPAN, text, ranges)
        return ranges
    }

    private static void addMatchRanges(Pattern pattern, String text, List<int[]> ranges) {
        Matcher matcher = pattern.matcher(text)
        while (matcher.find()) {
            ranges << ([matcher.start(), matcher.end()] as int[])
        }
    }

    private static boolean overlapsAnyRange(int start, int end, List<int[]> ranges) {
        for (int[] range : ranges) {
            if (start < range[1] && end > range[0]) {
                return true
            }
        }
        return false
    }

    /**
     * Builds a GFM Markdown pipe table from a correctly-bounded
     * {@code <table>...</table>} substring, or returns {@code null} if no
     * rows/cells could be found (malformed table). Row/cell structure and
     * text content are extracted via {@link TableExtractionPolicy}, which
     * never reads tag attributes at all.
     */
    private static String buildMarkdownTable(String tableHtml) {
        TableExtractionPolicy policy = new TableExtractionPolicy()
        HtmlSanitizer.sanitize(tableHtml, policy)
        List<RowData> rows = policy.rows
        if (rows.isEmpty()) {
            return null
        }
        RowData header = findHeaderRow(rows)
        if (header.cells.isEmpty()) {
            return null
        }
        // Use the widest row (e.g. a colspan'd header next to wider data
        // rows) as the column count and pad every row to it -- otherwise a
        // narrower header fixes the table's width and GFM silently drops
        // any extra cells in wider rows.
        int columnCount = rows*.cells*.size().max()
        StringBuilder sb = new StringBuilder()
        sb.append(rowLine(padCells(header.cells, columnCount))).append('\n')
        sb.append(delimiterLine(columnCount)).append('\n')
        for (RowData row : rows) {
            if (!row.is(header)) {
                sb.append(rowLine(padCells(row.cells, columnCount))).append('\n')
            }
        }
        return sb.toString().trim()
    }

    private static List<String> padCells(List<String> cells, int columnCount) {
        if (cells.size() >= columnCount) {
            return cells
        }
        List<String> padded = new ArrayList<>(cells)
        while (padded.size() < columnCount) {
            padded << ''
        }
        return padded
    }

    /**
     * The first row using {@code <th>} cells becomes the Markdown header
     * row. If no row uses {@code <th>}, the first row is used as the header,
     * since GFM pipe table syntax structurally requires one -- no additional
     * header styling is applied beyond what that syntax implies.
     */
    private static RowData findHeaderRow(List<RowData> rows) {
        for (RowData row : rows) {
            if (row.header) {
                return row
            }
        }
        return rows.get(0)
    }

    private static String rowLine(List<String> cells) {
        StringBuilder sb = new StringBuilder('|')
        for (String cell : cells) {
            sb.append(' ').append(escapeCell(cell)).append(' |')
        }
        return sb.toString()
    }

    private static String delimiterLine(int columnCount) {
        StringBuilder sb = new StringBuilder('|')
        for (int i = 0; i < columnCount; i++) {
            sb.append(' --- |')
        }
        return sb.toString()
    }

    /**
     * All ASCII punctuation characters CommonMark recognizes as
     * backslash-escapable (the same set the spec allows anywhere as a
     * literal escape). Escaping every one of them -- not just {@code |} --
     * is what keeps extracted cell text inert: without this, literal text
     * such as {@code ![x](https://attacker.example/leak)} would be parsed
     * as a live Markdown image by the renderer this table text is handed
     * to, and the sanitizer's image policy would let the browser issue that
     * request merely by rendering the page.
     */
    private static final String MARKDOWN_PUNCTUATION = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

    /**
     * Backslash-escapes every CommonMark-significant punctuation character
     * in extracted cell text, so none of it can be reinterpreted as
     * Markdown formatting, links, images, or code spans by the renderer.
     */
    private static String escapeCell(String text) {
        StringBuilder sb = new StringBuilder(text.length())
        for (char c : text.toCharArray()) {
            if (MARKDOWN_PUNCTUATION.indexOf((int) c) >= 0) {
                sb.append('\\')
            }
            sb.append(c)
        }
        return sb.toString()
    }

    /**
     * Streams a correctly-bounded {@code <table>...</table>} substring
     * through the OWASP HTML Sanitizer's tokenizer and collects its row/cell
     * text structure. Tag attributes are never read from {@code openTag}'s
     * {@code attrs} parameter -- it is ignored entirely -- so no attribute
     * value, quoted or not, can ever reach the output.
     */
    private static class TableExtractionPolicy implements HtmlSanitizer.Policy {
        List<RowData> rows = []
        private RowData currentRow
        private StringBuilder currentCellText
        private boolean currentCellIsHeader

        @Override
        void openDocument() {
        }

        @Override
        void closeDocument() {
        }

        // Any tag other than tr/td/th (e.g. a nested <span>) is ignored here;
        // its own text content still reaches text() below and is appended to
        // whatever cell is currently open.
        @Override
        void openTag(String elementName, List<String> attrs) {
            switch (elementName) {
                case 'tr':
                    currentRow = new RowData()
                    break
                case 'td':
                case 'th':
                    currentCellText = new StringBuilder()
                    currentCellIsHeader = elementName == 'th'
                    break
            }
        }

        @Override
        void closeTag(String elementName) {
            switch (elementName) {
                case 'tr':
                    if (currentRow != null && !currentRow.cells.isEmpty()) {
                        rows << currentRow
                    }
                    currentRow = null
                    break
                case 'td':
                case 'th':
                    closeCell()
                    break
            }
        }

        private void closeCell() {
            if (currentCellText != null && currentRow != null) {
                String cellText = WHITESPACE_RUN.matcher(currentCellText.toString()).replaceAll(' ').trim()
                currentRow.cells << cellText
                if (currentCellIsHeader) {
                    currentRow.header = true
                }
            }
            currentCellText = null
        }

        @Override
        void text(String textChunk) {
            if (currentCellText != null) {
                currentCellText.append(textChunk)
            }
        }
    }
}
