/*
 * Copyright 2026 SimplifyOps Inc, <http://simplifyops.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.rundeck.util

import groovy.transform.CompileStatic

import java.util.regex.Matcher
import java.util.regex.Pattern

/**
 * Converts hand-written HTML {@code <table>} blocks found inside raw job
 * description text into an equivalent GFM (GitHub Flavored Markdown) pipe
 * table, so that it can be rendered by the existing, unmodified
 * {@code rundeck.codecs.MarkdownCodec} -&gt; {@code rundeck.codecs.SanitizedHTMLCodec}
 * pipeline exactly as if the user had typed Markdown table syntax themselves.
 * <p>
 * {@code MarkdownCodec} deliberately escapes raw inline/block HTML as text
 * rather than rendering it live, to prevent attacker-controlled HTML/CSS
 * from reaching the sanitizer as executable markup. This class is kept
 * intentionally isolated from both codecs so that guarantee is never
 * weakened: it extracts only the plain text content of each table cell --
 * discarding every tag and attribute entirely -- and rebuilds a Markdown
 * pipe table from that text. No user-authored tag or attribute is ever
 * copied into the output; only plain text wrapped in Markdown syntax
 * generated by this class. It is meant to be called as a pre-processing
 * step on raw description text, before that text is handed to
 * {@code <g:markdown>}.
 */
@CompileStatic
class HtmlTableToMarkdownConverter {

    private static final Pattern TABLE_OPEN_TAG = Pattern.compile('<table\\b', Pattern.CASE_INSENSITIVE)
    private static final Pattern TABLE_CLOSE_TAG = Pattern.compile('</table\\s*>', Pattern.CASE_INSENSITIVE)
    private static final Pattern TABLE_BLOCK = Pattern.compile(
        '<table\\b[^>]*>(.*?)</table\\s*>',
        Pattern.CASE_INSENSITIVE | Pattern.DOTALL
    )
    private static final Pattern ROW_BLOCK = Pattern.compile(
        '<tr\\b[^>]*>(.*?)</tr\\s*>',
        Pattern.CASE_INSENSITIVE | Pattern.DOTALL
    )
    private static final Pattern CELL_BLOCK = Pattern.compile(
        '<th\\b[^>]*>(.*?)</th\\s*>|<td\\b[^>]*>(.*?)</td\\s*>',
        Pattern.CASE_INSENSITIVE | Pattern.DOTALL
    )
    private static final Pattern ANY_TAG = Pattern.compile('<[^>]*>')
    private static final Pattern WHITESPACE_RUN = Pattern.compile('\\s+')

    /**
     * Holds the extracted plain-text cells of a single {@code <tr>} row, and
     * whether the row used {@code <th>} cells (i.e. is a header row).
     */
    private static class RowData {
        boolean header
        List<String> cells = []
    }

    /**
     * Pre-processes raw description text: detects well-formed HTML
     * {@code <table>} blocks and replaces each one, in place, with an
     * equivalent GFM Markdown pipe table built only from the plain-text
     * content of each cell. Text outside of {@code <table>} blocks -- and
     * any other raw HTML tag -- is left completely untouched.
     * <p>
     * Fails safe: if the input contains unbalanced {@code <table>} tags, or
     * any table cannot be meaningfully parsed into rows/cells, the original
     * text is returned unchanged rather than throwing or emitting partial
     * output.
     *
     * @param text raw description text, possibly containing hand-written HTML tables
     * @return text with any detected HTML tables replaced by Markdown tables,
     *         or the original text unchanged if nothing was converted or a
     *         parse problem was detected
     */
    static String convert(String text) {
        if (!text) {
            return text
        }
        if (!hasBalancedTableTags(text)) {
            return text
        }
        try {
            return replaceTables(text)
        } catch (Exception ignored) {
            // Fail safe: never throw, never emit partial output.
            return text
        }
    }

    private static boolean hasBalancedTableTags(String text) {
        return countMatches(TABLE_OPEN_TAG, text) == countMatches(TABLE_CLOSE_TAG, text)
    }

    private static int countMatches(Pattern pattern, String text) {
        Matcher matcher = pattern.matcher(text)
        int count = 0
        while (matcher.find()) {
            count++
        }
        return count
    }

    private static String replaceTables(String text) {
        Matcher matcher = TABLE_BLOCK.matcher(text)
        StringBuilder result = new StringBuilder()
        int lastEnd = 0
        boolean convertedAny = false
        while (matcher.find()) {
            String markdownTable = buildMarkdownTable(matcher.group(1))
            if (markdownTable == null) {
                // A detected table could not be parsed into a meaningful
                // structure -- fail safe for the whole text rather than
                // emit a partially-converted result.
                return text
            }
            result.append(text, lastEnd, matcher.start())
            result.append('\n\n').append(markdownTable).append('\n\n')
            lastEnd = matcher.end()
            convertedAny = true
        }
        if (!convertedAny) {
            return text
        }
        result.append(text, lastEnd, text.length())
        return result.toString()
    }

    /**
     * Builds a GFM Markdown pipe table from the inner HTML of a
     * {@code <table>} element, or returns {@code null} if no rows/cells
     * could be found (malformed table).
     */
    private static String buildMarkdownTable(String tableInnerHtml) {
        List<RowData> rows = extractRows(tableInnerHtml)
        if (rows.isEmpty()) {
            return null
        }
        RowData header = findHeaderRow(rows)
        List<String> headerCells = header.cells
        if (headerCells.isEmpty()) {
            return null
        }
        StringBuilder sb = new StringBuilder()
        sb.append(rowLine(headerCells)).append('\n')
        sb.append(delimiterLine(headerCells.size())).append('\n')
        for (RowData row : rows) {
            if (!row.is(header)) {
                sb.append(rowLine(row.cells)).append('\n')
            }
        }
        return sb.toString().trim()
    }

    /**
     * The first row using {@code <th>} cells becomes the Markdown header
     * row. If no row uses {@code <th>}, the first row is used as the header,
     * since GFM pipe table syntax structurally requires one -- no additional
     * header styling is applied beyond what that syntax implies.
     */
    private static RowData findHeaderRow(List<RowData> rows) {
        for (RowData row : rows) {
            if (row.header) {
                return row
            }
        }
        return rows.get(0)
    }

    private static List<RowData> extractRows(String tableInnerHtml) {
        List<RowData> rows = []
        Matcher rowMatcher = ROW_BLOCK.matcher(tableInnerHtml)
        while (rowMatcher.find()) {
            RowData row = extractRow(rowMatcher.group(1))
            if (!row.cells.isEmpty()) {
                rows << row
            }
        }
        return rows
    }

    private static RowData extractRow(String rowHtml) {
        RowData row = new RowData()
        Matcher cellMatcher = CELL_BLOCK.matcher(rowHtml)
        while (cellMatcher.find()) {
            String headerCellHtml = cellMatcher.group(1)
            if (headerCellHtml != null) {
                row.header = true
                row.cells << extractCellText(headerCellHtml)
            } else {
                row.cells << extractCellText(cellMatcher.group(2))
            }
        }
        return row
    }

    /**
     * Extracts the plain-text content of a single cell: every tag (and with
     * it, every attribute) is discarded entirely -- never copied to the
     * output -- and remaining whitespace/newlines are collapsed to single
     * spaces so the text fits on one Markdown table row line.
     */
    private static String extractCellText(String cellHtml) {
        String withoutTags = ANY_TAG.matcher(cellHtml).replaceAll(' ')
        return WHITESPACE_RUN.matcher(withoutTags).replaceAll(' ').trim()
    }

    private static String rowLine(List<String> cells) {
        StringBuilder sb = new StringBuilder('|')
        for (String cell : cells) {
            sb.append(' ').append(escapeCell(cell)).append(' |')
        }
        return sb.toString()
    }

    private static String delimiterLine(int columnCount) {
        StringBuilder sb = new StringBuilder('|')
        for (int i = 0; i < columnCount; i++) {
            sb.append(' --- |')
        }
        return sb.toString()
    }

    /**
     * Escapes characters that are structurally significant to GFM pipe
     * table syntax so extracted cell text can never break out of its cell.
     */
    private static String escapeCell(String text) {
        return text.replace('\\', '\\\\').replace('|', '\\|')
    }
}
