/*
 * Copyright 2026 SimplifyOps Inc, <http://simplifyops.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.rundeck.util

import groovy.transform.CompileStatic
import org.owasp.html.HtmlSanitizer

import java.util.regex.Matcher
import java.util.regex.Pattern

/**
 * Converts hand-written HTML {@code <table>} blocks found inside raw job
 * description text into an equivalent GFM (GitHub Flavored Markdown) pipe
 * table, so that it can be rendered by the existing, unmodified
 * {@code rundeck.codecs.MarkdownCodec} -&gt; {@code rundeck.codecs.SanitizedHTMLCodec}
 * pipeline exactly as if the user had typed Markdown table syntax themselves.
 * <p>
 * {@code MarkdownCodec} deliberately escapes raw inline/block HTML as text
 * rather than rendering it live, to prevent attacker-controlled HTML/CSS
 * from reaching the sanitizer as executable markup. This class is kept
 * intentionally isolated from both codecs so that guarantee is never
 * weakened: it extracts only the plain text content of each table cell --
 * discarding every tag and attribute entirely -- and rebuilds a Markdown
 * pipe table from that text. No user-authored tag or attribute is ever
 * copied into the output; only plain text wrapped in Markdown syntax
 * generated by this class. It is meant to be called as a pre-processing
 * step on raw description text, before that text is handed to
 * {@code <g:markdown>}.
 * <p>
 * Finding the boundaries of a {@code <table>} block, and the row/cell
 * structure inside it, is deliberately NOT done with ad-hoc regular
 * expressions: a regex cannot soundly track "am I inside a quoted attribute
 * value" across an entire document, and an asymmetry between how open tags,
 * close tags, and tag-counting handled quotes previously let an attacker
 * hide a fake closing tag inside a quoted attribute to truncate a match
 * early and smuggle live Markdown past this class entirely. Table
 * boundaries are instead found with a small, single-pass, quote-aware
 * scanner ({@link #findTopLevelTables}), and row/cell text is extracted by
 * feeding each correctly-bounded table through the OWASP HTML Sanitizer's
 * public streaming tokenizer ({@link HtmlSanitizer#sanitize}) -- the same
 * library and the same trust boundary {@code SanitizedHTMLCodec} already
 * relies on -- via a {@link TableExtractionPolicy} that never reads or
 * copies tag attributes anywhere.
 */
@CompileStatic
class HtmlTableToMarkdownConverter {

    private static final Pattern INLINE_CODE_SPAN = Pattern.compile('(`+).*?\\1')
    private static final Pattern WHITESPACE_RUN = Pattern.compile('\\s+')

    /**
     * Holds the extracted plain-text cells of a single {@code <tr>} row, and
     * whether the row used {@code <th>} cells (i.e. is a header row).
     */
    private static class RowData {
        boolean header
        List<String> cells = []
    }

    /**
     * The character range of one top-level {@code <table>...</table>} block
     * in the original text, as found by {@link #findTopLevelTables}.
     */
    private static class TableSpan {
        int start
        int end
        boolean nested
    }

    /**
     * Pre-processes raw description text: detects well-formed HTML
     * {@code <table>} blocks and replaces each one, in place, with an
     * equivalent GFM Markdown pipe table built only from the plain-text
     * content of each cell. Text outside of {@code <table>} blocks -- and
     * any other raw HTML tag -- is left completely untouched. A
     * {@code <table>} written inside a Markdown fenced code block or inline
     * code span is treated as a documented example, not live HTML, and is
     * never converted.
     * <p>
     * Fails safe: if the input contains unbalanced or nested {@code <table>}
     * tags, or any table cannot be meaningfully parsed into rows/cells, the
     * original text is returned unchanged rather than throwing or emitting
     * partial output.
     *
     * @param text raw description text, possibly containing hand-written HTML tables
     * @return text with any detected HTML tables replaced by Markdown tables,
     *         or the original text unchanged if nothing was converted or a
     *         parse problem was detected
     */
    static String convert(String text) {
        if (!text) {
            return text
        }
        try {
            return replaceTables(text)
        } catch (Exception ignored) {
            // Fail safe: never throw, never emit partial output.
            return text
        }
    }

    private static String replaceTables(String text) {
        List<int[]> codeRanges = findCodeRanges(text)
        List<TableSpan> spans = findTopLevelTables(text, codeRanges)
        if (spans.isEmpty()) {
            return text
        }
        StringBuilder result = new StringBuilder()
        int lastEnd = 0
        boolean convertedAny = false
        for (TableSpan span : spans) {
            if (span.nested) {
                // A <table> nested inside another <table> is not supported
                // -- fail safe for the whole text rather than risk an
                // incomplete or confusing partial conversion.
                return text
            }
            String markdownTable = buildMarkdownTable(text.substring(span.start, span.end))
            if (markdownTable == null) {
                // A detected table could not be parsed into a meaningful
                // structure -- fail safe for the whole text rather than
                // emit a partially-converted result.
                return text
            }
            result.append(text, lastEnd, span.start)
            appendMissingNewlines(result, countNewlinesBefore(text, span.start))
            result.append(markdownTable)
            appendMissingNewlines(result, countNewlinesAfter(text, span.end))
            lastEnd = span.end
            convertedAny = true
        }
        if (!convertedAny) {
            return text
        }
        result.append(text, lastEnd, text.length())
        return result.toString()
    }

    private static final int BLOCK_SEPARATION = 2

    /**
     * Appends only as many newlines as are missing to reach a full blank
     * line of separation (two newlines) around the generated table, instead
     * of always adding two: if the original text already had a blank line
     * at this boundary, nothing more is added, so converting a table never
     * introduces extra vertical whitespace that wasn't there before.
     */
    private static void appendMissingNewlines(StringBuilder result, int existing) {
        for (int n = existing; n < BLOCK_SEPARATION; n++) {
            result.append('\n')
        }
    }

    /**
     * How many of the up-to-{@link #BLOCK_SEPARATION} characters
     * immediately before {@code position} are newlines. Returns
     * {@link #BLOCK_SEPARATION} unchanged at the very start of the text --
     * there is nothing before the table to separate it from.
     */
    private static int countNewlinesBefore(String text, int position) {
        if (position == 0) {
            return BLOCK_SEPARATION
        }
        int count = 0
        int i = position - 1
        while (i >= 0 && count < BLOCK_SEPARATION && text.charAt(i) == '\n' as char) {
            count++
            i--
        }
        return count
    }

    /**
     * How many of the up-to-{@link #BLOCK_SEPARATION} characters
     * immediately after {@code position} are newlines. Returns
     * {@link #BLOCK_SEPARATION} unchanged at the very end of the text --
     * there is nothing after the table to separate it from.
     */
    private static int countNewlinesAfter(String text, int position) {
        int length = text.length()
        if (position == length) {
            return BLOCK_SEPARATION
        }
        int count = 0
        int i = position
        while (i < length && count < BLOCK_SEPARATION && text.charAt(i) == '\n' as char) {
            count++
            i++
        }
        return count
    }

    /**
     * Single-pass, quote-aware scan for top-level {@code <table>...</table>}
     * blocks. A quoted attribute value (single- or double-quoted) is skipped
     * as one unit when looking for a tag's closing {@code >}, so a
     * {@code >} -- or a fake {@code </table>} -- hidden inside one can never
     * be mistaken for real markup; an HTML comment is likewise skipped as one
     * unit up to its real {@code -->}. A table is marked {@code nested} if
     * another {@code <table>} opens before its matching close is found.
     * Any {@code <} found inside a Markdown fenced code block or inline code
     * span ({@code codeRanges}) is ignored entirely -- a table documented as
     * an example never participates in boundary-finding, so a stray,
     * unmatched tag in such an example cannot corrupt the depth-tracking for
     * a genuine table elsewhere in the text. An opening
     * {@code <script>}/{@code <style>}/{@code <textarea>}/{@code <title>}
     * tag is followed all the way to its real, matching closing tag: HTML
     * gives these elements "raw text" content -- everything up to that
     * closing tag is literal text, never markup -- so without this, a
     * {@code </table>} typed as literal script/style content would be
     * mistaken for a real closing tag the same way an unguarded quote or
     * comment was.
     */
    private static List<TableSpan> findTopLevelTables(String text, List<int[]> codeRanges) {
        List<TableSpan> spans = []
        int length = text.length()
        int i = 0
        int depth = 0
        int currentStart = -1
        boolean nestedSeen = false
        while (i < length) {
            char c = text.charAt(i)
            if (c != '<' as char) {
                i++
                continue
            }
            if (!isTagStart(text, i)) {
                // A literal "<" in ordinary prose (e.g. "1 < 2") is not a
                // tag at all. Treating it as one would make skipTag consume
                // everything up to the next unquoted ">" -- which, more
                // often than not, belongs to a real tag further along --
                // silently absorbing that tag so it's never recognized on
                // its own (e.g. a genuinely nested <table> right after it).
                i++
                continue
            }
            if (depth == 0 && isPositionInAnyRange(i, codeRanges)) {
                // Code-range skipping only applies while deciding whether to
                // START tracking a table (depth zero): that's the "is this
                // whole table just a documented example" question. Once
                // we're already inside a real table (depth > 0), a `<table`
                // hidden in a code span must be treated as genuine nesting,
                // not silently ignored -- otherwise its closing tag can
                // still end the real table's depth-tracking early while the
                // attacker-controlled text after the hidden opening tag is
                // left unescaped outside the (truncated) match.
                i++
                continue
            }
            boolean isOpenTable = isTagNamed(text, i, 'table', false)
            boolean isCloseTable = isTagNamed(text, i, 'table', true)
            int tagEnd = skipTag(text, i)
            if (tagEnd < 0) {
                // Unterminated tag: stop scanning, nothing further can be
                // trusted as a complete table.
                break
            }
            if (!isCloseTable) {
                String rawTextElement = rawTextElementName(text, i)
                if (rawTextElement != null) {
                    int rawTextEnd = skipRawTextElement(text, tagEnd, rawTextElement)
                    if (rawTextEnd < 0) {
                        // The raw-text element's own closing tag is never
                        // found: nothing further can be trusted.
                        break
                    }
                    tagEnd = rawTextEnd
                }
            }
            if (isOpenTable) {
                if (depth == 0) {
                    currentStart = i
                    nestedSeen = false
                } else {
                    nestedSeen = true
                }
                depth++
            } else if (isCloseTable && depth > 0) {
                depth--
                if (depth == 0) {
                    spans << new TableSpan(start: currentStart, end: tagEnd, nested: nestedSeen)
                }
            }
            i = tagEnd
        }
        return spans
    }

    /**
     * Given the index of a {@code <} character, returns the index just past
     * the tag's matching, quote-aware {@code >} -- a {@code >} inside a
     * single- or double-quoted attribute value does not end the tag.
     * An HTML comment ({@code <!--...-->}) is recognized up front and
     * skipped as one opaque unit up to its real {@code -->}: comments can
     * contain anything, including quotes and {@code >} characters, with no
     * escaping, so treating them like an ordinary tag would let a {@code >}
     * inside a comment end the scan early and leak the rest of the comment
     * (and whatever follows) as unescaped trailing text.
     * Returns -1 if the tag/comment is never closed (truncated/malformed
     * input).
     */
    private static final char NO_QUOTE = (char) 0
    private static final String COMMENT_START = '<!--'
    private static final String COMMENT_END = '-->'

    /**
     * Whether the character after {@code ltIndex} (a {@code <}) is one that
     * can actually start a tag, comment, or declaration -- a letter (element
     * name), {@code /} (closing tag), {@code !} (comment/declaration), or
     * {@code ?} (processing instruction/bogus comment). Anything else means
     * the {@code <} is just a literal character in ordinary text (e.g. the
     * "less than" in {@code "1 < 2"}), not the start of markup at all.
     */
    private static boolean isTagStart(String text, int ltIndex) {
        int i = ltIndex + 1
        if (i >= text.length()) {
            return false
        }
        char next = text.charAt(i)
        return next == '/' as char || next == '!' as char || next == '?' as char || Character.isLetter(next)
    }

    private static int skipTag(String text, int ltIndex) {
        if (text.regionMatches(ltIndex, COMMENT_START, 0, COMMENT_START.length())) {
            int closeIndex = text.indexOf(COMMENT_END, ltIndex + COMMENT_START.length())
            return closeIndex < 0 ? -1 : closeIndex + COMMENT_END.length()
        }
        int length = text.length()
        int i = ltIndex + 1
        char quote = NO_QUOTE
        while (i < length) {
            char c = text.charAt(i)
            if (quote != NO_QUOTE) {
                if (c == quote) {
                    quote = NO_QUOTE
                }
            } else if (c == '"' as char || c == '\'' as char) {
                quote = c
            } else if (c == '>' as char) {
                return i + 1
            }
            i++
        }
        return -1
    }

    /**
     * Whether the tag starting at {@code ltIndex} (a {@code <} character) is
     * specifically an open (or, if {@code closing}, a close) tag for
     * {@code name}, case-insensitively, as opposed to some other tag whose
     * name happens to start with the same letters (e.g. {@code <tablecloth>}).
     */
    private static boolean isTagNamed(String text, int ltIndex, String name, boolean closing) {
        int length = text.length()
        int i = ltIndex + 1
        if (closing) {
            if (i >= length || text.charAt(i) != '/' as char) {
                return false
            }
            i++
        }
        if (!text.regionMatches(true, i, name, 0, name.length())) {
            return false
        }
        int after = i + name.length()
        if (after >= length) {
            return true
        }
        char next = text.charAt(after)
        return Character.isWhitespace(next) || next == '>' as char || next == '/' as char
    }

    private static final Set<String> RAW_TEXT_ELEMENTS = ['script', 'style', 'textarea', 'title'] as Set<String>

    /**
     * If the opening tag starting at {@code ltIndex} is one of
     * {@link #RAW_TEXT_ELEMENTS}, returns its lowercase name; otherwise
     * {@code null}.
     */
    private static String rawTextElementName(String text, int ltIndex) {
        int length = text.length()
        int i = ltIndex + 1
        int nameStart = i
        while (i < length) {
            char c = text.charAt(i)
            if (Character.isWhitespace(c) || c == '>' as char || c == '/' as char) {
                break
            }
            i++
        }
        String name = text.substring(nameStart, i).toLowerCase(Locale.ROOT)
        return RAW_TEXT_ELEMENTS.contains(name) ? name : null
    }

    /**
     * Given {@code contentStart} (just past a raw-text element's own opening
     * {@code >}), returns the index just past that element's real, matching
     * closing tag (e.g. {@code </script>}), found case-insensitively and
     * confirmed to be followed only by optional whitespace and {@code >} --
     * not merely the element name appearing as part of a longer word.
     * Returns -1 if no such closing tag is found.
     */
    private static int skipRawTextElement(String text, int contentStart, String elementName) {
        String closeTag = '</' + elementName
        int length = text.length()
        int searchFrom = contentStart
        while (searchFrom <= length - closeTag.length()) {
            int idx = indexOfIgnoreCase(text, closeTag, searchFrom)
            if (idx < 0) {
                return -1
            }
            int j = idx + closeTag.length()
            while (j < length && Character.isWhitespace(text.charAt(j))) {
                j++
            }
            if (j < length && text.charAt(j) == '>' as char) {
                return j + 1
            }
            searchFrom = idx + 1
        }
        return -1
    }

    private static int indexOfIgnoreCase(String text, String needle, int fromIndex) {
        int length = text.length()
        int needleLength = needle.length()
        for (int i = fromIndex; i <= length - needleLength; i++) {
            if (text.regionMatches(true, i, needle, 0, needleLength)) {
                return i
            }
        }
        return -1
    }

    /**
     * Finds the character ranges of Markdown fenced code blocks and inline
     * code spans in {@code text}, so {@link #findTopLevelTables} can ignore
     * any {@code <table>}-like text found inside them -- those are
     * documented examples, not raw HTML meant to be rendered live.
     */
    private static List<int[]> findCodeRanges(String text) {
        List<int[]> ranges = findFencedCodeBlocks(text)
        addMatchRanges(INLINE_CODE_SPAN, text, ranges)
        return ranges
    }

    /**
     * Finds fenced code block ranges per the CommonMark spec: an opening
     * fence of 3+ backticks or tildes (up to 3 leading spaces) at the start
     * of a line, closed by a line (also up to 3 leading spaces, optionally
     * followed only by trailing whitespace) of the SAME fence character with
     * length greater than or equal to the opening fence's length -- not
     * necessarily equal. An unclosed fence extends to the end of the text.
     */
    private static List<int[]> findFencedCodeBlocks(String text) {
        List<int[]> ranges = []
        int length = text.length()
        int lineStart = 0
        while (lineStart < length) {
            int lineEnd = text.indexOf('\n', lineStart)
            if (lineEnd < 0) {
                lineEnd = length
            }
            int[] fence = matchFence(text, lineStart, lineEnd, NO_QUOTE, 0)
            if (fence != null) {
                char fenceChar = (char) fence[0]
                int fenceLen = fence[1]
                int blockEnd = length
                int closeLineStart = lineEnd < length ? lineEnd + 1 : length
                while (closeLineStart < length) {
                    int closeLineEnd = text.indexOf('\n', closeLineStart)
                    if (closeLineEnd < 0) {
                        closeLineEnd = length
                    }
                    if (matchFence(text, closeLineStart, closeLineEnd, fenceChar, fenceLen) != null) {
                        blockEnd = closeLineEnd < length ? closeLineEnd + 1 : length
                        break
                    }
                    closeLineStart = closeLineEnd < length ? closeLineEnd + 1 : length
                }
                ranges << ([lineStart, blockEnd] as int[])
                lineStart = blockEnd
            } else {
                lineStart = lineEnd < length ? lineEnd + 1 : length
            }
        }
        return ranges
    }

    /**
     * Checks whether the line {@code [lineStart, lineEnd)} is a fence line:
     * up to 3 leading spaces, then a run of 3+ of the same fence character
     * (backtick or tilde). When {@code requiredChar} is {@link #NO_QUOTE},
     * any fence character/length qualifies as an OPENING fence and both are
     * returned as {@code [char, length]}; otherwise this checks for a
     * CLOSING fence of exactly {@code requiredChar} with length greater than
     * or equal to {@code requiredMinLength}, with only whitespace allowed
     * after the fence run, returning a non-null sentinel on success.
     */
    private static int[] matchFence(String text, int lineStart, int lineEnd, char requiredChar, int requiredMinLength) {
        int i = lineStart
        int spaces = 0
        while (i < lineEnd && spaces < 3 && text.charAt(i) == ' ' as char) {
            i++
            spaces++
        }
        if (i >= lineEnd) {
            return null
        }
        char c = text.charAt(i)
        if (c != '`' as char && c != '~' as char) {
            return null
        }
        if (requiredChar != NO_QUOTE && c != requiredChar) {
            return null
        }
        int runStart = i
        while (i < lineEnd && text.charAt(i) == c) {
            i++
        }
        int runLength = i - runStart
        if (runLength < 3 || (requiredChar != NO_QUOTE && runLength < requiredMinLength)) {
            return null
        }
        if (requiredChar != NO_QUOTE) {
            // A closing fence line may have nothing but whitespace after the
            // fence run.
            while (i < lineEnd) {
                if (!Character.isWhitespace(text.charAt(i))) {
                    return null
                }
                i++
            }
        }
        return [(int) c, runLength] as int[]
    }

    private static void addMatchRanges(Pattern pattern, String text, List<int[]> ranges) {
        Matcher matcher = pattern.matcher(text)
        while (matcher.find()) {
            ranges << ([matcher.start(), matcher.end()] as int[])
        }
    }

    private static boolean isPositionInAnyRange(int position, List<int[]> ranges) {
        for (int[] range : ranges) {
            if (position >= range[0] && position < range[1]) {
                return true
            }
        }
        return false
    }

    /**
     * Builds a GFM Markdown pipe table from a correctly-bounded
     * {@code <table>...</table>} substring, or returns {@code null} if no
     * rows/cells could be found (malformed table). Row/cell structure and
     * text content are extracted via {@link TableExtractionPolicy}, which
     * never reads tag attributes at all.
     */
    private static String buildMarkdownTable(String tableHtml) {
        TableExtractionPolicy policy = new TableExtractionPolicy()
        HtmlSanitizer.sanitize(tableHtml, policy)
        List<RowData> rows = policy.rows
        if (rows.isEmpty()) {
            return null
        }
        RowData header = findHeaderRow(rows)
        if (header.cells.isEmpty()) {
            return null
        }
        // Use the widest row (e.g. a colspan'd header next to wider data
        // rows) as the column count and pad every row to it -- otherwise a
        // narrower header fixes the table's width and GFM silently drops
        // any extra cells in wider rows.
        int columnCount = rows*.cells*.size().max()
        StringBuilder sb = new StringBuilder()
        sb.append(rowLine(padCells(header.cells, columnCount))).append('\n')
        sb.append(delimiterLine(columnCount)).append('\n')
        for (RowData row : rows) {
            if (!row.is(header)) {
                sb.append(rowLine(padCells(row.cells, columnCount))).append('\n')
            }
        }
        return sb.toString().trim()
    }

    private static List<String> padCells(List<String> cells, int columnCount) {
        if (cells.size() >= columnCount) {
            return cells
        }
        List<String> padded = new ArrayList<>(cells)
        while (padded.size() < columnCount) {
            padded << ''
        }
        return padded
    }

    /**
     * The first row using {@code <th>} cells becomes the Markdown header
     * row. If no row uses {@code <th>}, the first row is used as the header,
     * since GFM pipe table syntax structurally requires one -- no additional
     * header styling is applied beyond what that syntax implies.
     */
    private static RowData findHeaderRow(List<RowData> rows) {
        for (RowData row : rows) {
            if (row.header) {
                return row
            }
        }
        return rows.get(0)
    }

    private static String rowLine(List<String> cells) {
        StringBuilder sb = new StringBuilder('|')
        for (String cell : cells) {
            sb.append(' ').append(escapeCell(cell)).append(' |')
        }
        return sb.toString()
    }

    private static String delimiterLine(int columnCount) {
        StringBuilder sb = new StringBuilder('|')
        for (int i = 0; i < columnCount; i++) {
            sb.append(' --- |')
        }
        return sb.toString()
    }

    /**
     * All ASCII punctuation characters CommonMark recognizes as
     * backslash-escapable (the same set the spec allows anywhere as a
     * literal escape). Escaping every one of them -- not just {@code |} --
     * is what keeps extracted cell text inert: without this, literal text
     * such as {@code ![x](https://attacker.example/leak)} would be parsed
     * as a live Markdown image by the renderer this table text is handed
     * to, and the sanitizer's image policy would let the browser issue that
     * request merely by rendering the page.
     */
    private static final String MARKDOWN_PUNCTUATION = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

    /**
     * Backslash-escapes every CommonMark-significant punctuation character
     * in extracted cell text, so none of it can be reinterpreted as
     * Markdown formatting, links, images, or code spans by the renderer.
     */
    private static String escapeCell(String text) {
        StringBuilder sb = new StringBuilder(text.length())
        for (char c : text.toCharArray()) {
            if (MARKDOWN_PUNCTUATION.indexOf((int) c) >= 0) {
                sb.append('\\')
            }
            sb.append(c)
        }
        return sb.toString()
    }

    /**
     * Streams a correctly-bounded {@code <table>...</table>} substring
     * through the OWASP HTML Sanitizer's tokenizer and collects its row/cell
     * text structure. Tag attributes are never read from {@code openTag}'s
     * {@code attrs} parameter -- it is ignored entirely -- so no attribute
     * value, quoted or not, can ever reach the output.
     */
    private static class TableExtractionPolicy implements HtmlSanitizer.Policy {
        List<RowData> rows = []
        private RowData currentRow
        private StringBuilder currentCellText
        private boolean currentCellIsHeader

        @Override
        void openDocument() {
        }

        @Override
        void closeDocument() {
        }

        // Any tag other than tr/td/th/br (e.g. a nested <span>) is ignored
        // here; its own text content still reaches text() below and is
        // appended to whatever cell is currently open.
        @Override
        void openTag(String elementName, List<String> attrs) {
            switch (elementName) {
                case 'tr':
                    currentRow = new RowData()
                    break
                case 'td':
                case 'th':
                    currentCellText = new StringBuilder()
                    currentCellIsHeader = elementName == 'th'
                    break
                case 'br':
                    // A line break has no text content of its own, so without
                    // this the text before and after it would otherwise be
                    // concatenated with nothing between them.
                    if (currentCellText != null) {
                        currentCellText.append(' ')
                    }
                    break
            }
        }

        @Override
        void closeTag(String elementName) {
            switch (elementName) {
                case 'tr':
                    if (currentRow != null && !currentRow.cells.isEmpty()) {
                        rows << currentRow
                    }
                    currentRow = null
                    break
                case 'td':
                case 'th':
                    closeCell()
                    break
            }
        }

        private void closeCell() {
            if (currentCellText != null && currentRow != null) {
                String cellText = WHITESPACE_RUN.matcher(currentCellText.toString()).replaceAll(' ').trim()
                currentRow.cells << cellText
                if (currentCellIsHeader) {
                    currentRow.header = true
                }
            }
            currentCellText = null
        }

        @Override
        void text(String textChunk) {
            if (currentCellText != null) {
                currentCellText.append(textChunk)
            }
        }
    }
}
