version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_exclude:
          regex: '(needs documentation)'
          message: 'This PR needs documentation. Please submit a PR to the https://github.com/rundeck/docs project with your documentation.'
  - when: pull_request.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: 'Please describe the changes'
