pull_request_rules:
  # Backport to maint(version) branches
  - name: backport patches to 3.0 maint branch
    conditions:
      - base=main
      - label=backport-to-3.0
    actions:
      backport:
        branches:
          - maint-3.0.x
  - name: backport patches to 3.1 maint branch
    conditions:
      - base=main
      - label=backport-to-3.1
    actions:
      backport:
        branches:
          - maint-3.1.x
  - name: backport patches to 3.2 maint branch
    conditions:
      - base=main
      - label=backport-to-3.2
    actions:
      backport:
        branches:
          - maint-3.2.x
  - name: backport patches to 3.3 maint branch
    conditions:
      - base=main
      - label=backport-to-3.3
    actions:
      backport:
        branches:
          - maint-3.3.x
  - name: backport patches to 3.4 maint branch
    conditions:
      - base=main
      - label=backport-to-3.4
    actions:
      backport:
        branches:
          - maint-3.4.x
  - name: backport patches to main
    conditions:
      - label=backport-to-main
    actions:
      backport:
        branches:
          - main
  - name: backport patches to 2.11 maint branch
    conditions:
      - base=main
      - label=backport-to-2.11
    actions:
      backport:
        branches:
          - release-2.11
  # Add version labels to open PRs
  - name: label PRs main with 4.x
    conditions:
      - base=main
      - -closed
    actions:
      label:
        add: [4.x]
  - name: label PRs to 3.4 maint branch
    conditions:
      - base=maint-3.4.x
      - -closed
    actions:
      label:
        add: [ 3.4.x ]
  - name: label PRs to 3.3 maint branch
    conditions:
      - base=maint-3.3.x
      - -closed
    actions:
      label:
        add: [ 3.3.x ]
  - name: label PRs to 3.2 maint branch
    conditions:
      - base=maint-3.2.x
      - -closed
    actions:
      label:
        add: [3.2.x]
  - name: label PRs to 3.1 maint branch
    conditions:
      - base=maint-3.1.x
      - -closed
    actions:
      label:
        add: [3.1.x]
