---
rundeck:
  plugins: # Extra plugins to bundle
  - "com.github.Batix:rundeck-ansible-plugin:3.1.0"
  - "com.github.rundeck-plugins:aws-s3-model-source:v1.0.4"
  - "com.github.rundeck-plugins:py-winrm-plugin:2.0.6"
  - "com.github.rundeck-plugins:openssh-node-execution:2.0.0"
  - "com.github.rundeck-plugins:multiline-regex-datacapture-filter:1.0.0"
  - "com.github.rundeck-plugins:attribute-match-node-enhancer:v0.1.5"
