---
rundeck:
  plugins: # Extra plugins to bundle
  - "org.rundeck.plugins:ansible-plugin:5.0.0"
  - "org.rundeck.plugins:aws-s3-model-source:2.0.0"
  - "org.rundeck.plugins:py-winrm-plugin:3.0.0"
  - "org.rundeck.plugins:openssh-node-execution:3.0.0"
  - "org.rundeck.plugins:multiline-regex-datacapture-filter:2.0.0"
  - "org.rundeck.plugins:attribute-match-node-enhancer:1.0.0"
  - "org.rundeck.plugins:sshj-plugin:1.0.0"
