---
rundeck:
  plugins: # Extra plugins to bundle
  - "com.github.rundeck-plugins:ansible-plugin:4.0.7"
  - "com.github.rundeck-plugins:aws-s3-model-source:v1.0.9"
  - "com.github.rundeck-plugins:py-winrm-plugin:2.1.3@zip"
  - "com.github.rundeck-plugins:openssh-node-execution:2.0.3@zip"
  - "com.github.rundeck-plugins:multiline-regex-datacapture-filter:1.1.0"
  - "org.rundeck.plugins:attribute-match-node-enhancer:0.2.0"
  - "com.github.rundeck-plugins:sshj-plugin:v0.1.17"
