---
rundeck:
  plugins: # Extra plugins to bundle
  - "com.github.rundeck-plugins:ansible-plugin:4.0.12-SNAPSHOT"
  - "org.rundeck.plugins:aws-s3-model-source:1.0.11-grails7-upgrade-SNAPSHOT"
  - "com.github.rundeck-plugins:py-winrm-plugin:2.1.4-SNAPSHOT@zip"
  - "com.github.rundeck-plugins:openssh-exec-plugin:2.0.5-SNAPSHOT@zip"
  - "org.rundeck.plugins:multiline-regex-datacapture-filter:1.1.6-grails7-upgrade-SNAPSHOT"
  - "org.rundeck.plugins:attribute-match-node-enhancer:0.2.4-grails7-upgrade-SNAPSHOT"
  - "org.rundeck.plugins:sshj-plugin:0.1.20-grails7-upgrade"
