name: example script-based node step plugin
version: 1.0
rundeckPluginVersion: 1.1
author: Greg Schueler
date: 12/7/12
providers:
  - name: example-node-step
    service: WorkflowNodeStep
    title: Example Script Node Step
    description: Does nothing
    mergeEnvironment: true
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: nodestep.sh
    script-args: '${node.name} ${config.example} ${config.asif} ${config.number} ${config.vampires}'
    config:
      - type: String
        name: example
        title: Example
        description: An example string
        default: whatever
      - type: String
        name: examplemulti
        title: Example Multiline
        description: An example string
        default: whatever
        renderingOptions:
          displayType: MULTI_LINE
      - type: Boolean
        name: asif
        title: As if
        description: If something
        default: true
      - type: Integer
        name: number
        title: Numbor
        description: A number for something
        default: 1
      - type: Select
        name: vampires
        title: Vampires
        description: What vampire
        default: albert
        values:
          - albert
          - ross
          - simon
          - bellfunkle
          - droom
      - type: String
        name: projectExample
        title: Example Project scope property
        description: An example string scoped to Project or Framework level configuration
        default: whatever
        scope: Project
      - type: String
        name: fwkExample
        title: Example Framework scope property
        description: An example string scoped to Framework level configuration with no default
        scope: Framework
