/*
 * Copyright 2019 Rundeck, Inc. (http://rundeck.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.rundeck.grails.plugins.securityheaders

import groovy.transform.CompileStatic

import jakarta.servlet.http.HttpServletRequest
import jakarta.servlet.http.HttpServletResponse

/**
 * reference:
 *
 *  https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#csp
 *  https://content-security-policy.com/
 *
 *  configuration:
 *
 *  `policy`: explicit policy string, if set individual directives will be ignored
 *  `<directive>`: individual directive values, see {@link CSPSecurityHeaderProvider#DIRECTIVES}
 *  `include-xcsp-header`: add policy in X-Content-Security-Policy header as well (default:true)
 *  `include-xwkcsp-header`: set policy in X-WebKit-CSP header as well (default:true)
 *
 *  Nonce support: a directive value may include the marker keyword `nonce` (e.g.
 *  `script-src: 'self nonce'`). The marker is only honored when `nonce-enabled: true` is also set
 *  in the provider config; in that case it is replaced with the per-request `'nonce-<value>'`
 *  source expression generated by {@link CspNonceProvider}, and the header is rebuilt for every
 *  request. When `nonce-enabled` is absent or false, the marker is instead replaced with
 *  `'unsafe-inline'` so inline scripts keep working, and the header is computed once and cached,
 *  preserving the previous (pre-nonce) behavior exactly. This makes nonce support opt-in.
 *
 */
@CompileStatic
class CSPSecurityHeaderProvider implements SecurityHeaderProvider {

    public static final String CSP_HEADER_NAME = 'Content-Security-Policy'
    public static final String XCSP_HEADER_NAME = 'X-Content-Security-Policy'
    public static final String X_WEBKIT_CSP_HEADER_NAME = 'X-WebKit-CSP'
    public static final String CONFIG_INCLUDE_X_CSP_HEADER = 'include-xcsp-header'
    public static final String CONFIG_INCLUDE_X_WEBKIT_CSP_HEADER = 'include-xwkcsp-header'
    public static final String CONFIG_POLICY = 'policy'
    /**
     * Config key which must be set to {@code true} for the {@link #NONCE_MARKER} keyword to be
     * honored. Makes nonce support opt-in; defaults to {@code false}.
     */
    public static final String CONFIG_NONCE_ENABLED = 'nonce-enabled'
    /**
     * Marker keyword which can be used as a directive source value to request that the
     * per-request nonce be injected into that directive, when {@link #CONFIG_NONCE_ENABLED} is set.
     */
    public static final String NONCE_MARKER = 'nonce'
    /**
     * Prefix of the CSP nonce source expression.
     */
    public static final String NONCE_PREFIX = 'nonce-'

    String name = 'csp'
    Boolean defaultEnabled = true
    Map<String, String> directives

    List<SecurityHeader> builtHeaders

    @Override
    List<SecurityHeader> getSecurityHeaders(
            final HttpServletRequest request,
            final HttpServletResponse response,
            Map config
    ) {
        buildHeaders(config, request)
    }

    /**
     * Build the CSP headers for the given configuration and request.
     *
     * <p>When the configuration requests a nonce (see {@link #NONCE_MARKER}) the headers are
     * rebuilt on every call, since the nonce value is unique per request. Otherwise the result is
     * computed once and cached for the lifetime of this provider.</p>
     *
     * @param config provider configuration
     * @param request current request, used to resolve the per-request nonce value
     * @return list of headers to add to the response
     */
    private List<SecurityHeader> buildHeaders(Map config, HttpServletRequest request) {
        if (isNonceRequested(config)) {
            return createHeaders(config, CspNonceProvider.getNonce(request))
        }
        if (null == builtHeaders) {
            synchronized (this) {
                if (builtHeaders == null) {
                    builtHeaders = createHeaders(config, null)
                }
            }
        }
        builtHeaders
    }

    /**
     * Create the header list for the given configuration.
     *
     * @param config provider configuration
     * @param nonce nonce value to substitute for the {@link #NONCE_MARKER} keyword, or null to
     *        simply drop the marker
     * @return list of headers
     */
    private List<SecurityHeader> createHeaders(Map config, String nonce) {
        String headerValue
        if (config.get(CONFIG_POLICY)) {
            //explicit policy definition
            headerValue = config.get(CONFIG_POLICY)
        } else {
            //define by directive name

            boolean nonceEnabled = getBoolean(config, CONFIG_NONCE_ENABLED, false)
            List<String> valueParts = []
            DIRECTIVES.each { String directive ->
                String val = config.get(directive)
                if (val) {
                    List<String> values = applyNonce(val.split(/\s+/).toList(), nonce, nonceEnabled)
                    String cspString = generateCspHeader(directive, values)
                    if (cspString) {
                        valueParts << cspString
                    }
                }
            }

            if (valueParts) {
                headerValue = valueParts.join(' ; ') + ' ;'
            } else {
                throw new IllegalStateException(
                        "$CONFIG_POLICY or directive configuration is required, directives: $DIRECTIVES"
                )
            }
        }
        List<SecurityHeader> built = []

        built << new SecurityHeaderImpl(name: CSP_HEADER_NAME, value: headerValue)
        if (getBoolean(config, CONFIG_INCLUDE_X_CSP_HEADER, false)) {
            built << new SecurityHeaderImpl(name: XCSP_HEADER_NAME, value: headerValue)
        }
        if (getBoolean(config, CONFIG_INCLUDE_X_WEBKIT_CSP_HEADER, false)) {
            built << new SecurityHeaderImpl(name: X_WEBKIT_CSP_HEADER_NAME, value: headerValue)
        }

        built
    }

    /**
     * Determine whether the configuration requests nonce injection, i.e. whether
     * {@link #CONFIG_NONCE_ENABLED} is true and any directive source list contains the
     * {@link #NONCE_MARKER} keyword. Ignored when an explicit `policy` string is configured.
     *
     * @param config provider configuration
     * @return true if a nonce should be generated per request
     */
    static boolean isNonceRequested(Map config) {
        if (config.get(CONFIG_POLICY)) {
            return false
        }
        if (!getBoolean(config, CONFIG_NONCE_ENABLED, false)) {
            return false
        }
        DIRECTIVES.any { String directive ->
            String val = config.get(directive)
            val && val.split(/\s+/).toList().any { String value -> isNonceMarker(value) }
        }
    }

    /**
     * @param value a configured directive source value
     * @return true if the value is the nonce marker keyword, optionally single-quoted
     */
    static boolean isNonceMarker(String value) {
        unquote(value) == NONCE_MARKER
    }

    /**
     * Replace the nonce marker keyword in a directive source list with the actual nonce source
     * expression, when nonce support is enabled. If no nonce value is available the marker is
     * dropped, so that a literal `'nonce'` is never emitted. When nonce support is not enabled,
     * the marker is instead replaced with `unsafe-inline`, preserving pre-nonce behavior.
     *
     * @param values configured directive source values
     * @param nonce nonce value, or null
     * @param nonceEnabled whether nonce support is enabled ({@link #CONFIG_NONCE_ENABLED})
     * @return source values with the marker resolved
     */
    static List<String> applyNonce(List<String> values, String nonce, boolean nonceEnabled) {
        List<String> result = []
        for (String value : values) {
            if (isNonceMarker(value)) {
                if (nonceEnabled) {
                    if (nonce) {
                        result << (NONCE_PREFIX + nonce)
                    }
                } else {
                    result << 'unsafe-inline'
                }
            } else {
                result << value
            }
        }
        result
    }

    /**
     * @param value source value
     * @return the value with surrounding single quotes removed, and trimmed
     */
    private static String unquote(String value) {
        String trimmed = value?.trim()
        if (trimmed?.length() > 1 && trimmed.startsWith("'") && trimmed.endsWith("'")) {
            return trimmed.substring(1, trimmed.length() - 1)
        }
        trimmed
    }

    static boolean getBoolean(final Map map, final String key, final boolean defVal) {
        if (null == map.get(key)) {
            return defVal
        }
        map.get(key) in [true, 'true']
    }

    static String generateCspHeader(String directive, List<String> allowed) {
        allowed = allowed?.findAll { it?.trim() }
        if (!allowed) {
            return null
        }
        directive + ' ' + allowed.collect {
            if (it in SRC_KEYWORDS || SRC_PREFIXES.any { pref -> it.startsWith(pref) }) {
                "'${it}'"
            } else {
                it
            }
        }.join(" ")
    }

    static final List<String> SRC_KEYWORDS = Collections.unmodifiableList(
            [
                    'none',
                    'self',
                    'unsafe-inline',
                    'unsafe-eval'
            ]
    )

    static final List<String> SRC_PREFIXES = Collections.unmodifiableList(
            [
                    'nonce-',
                    'sha256-',
            ]
    )

    static final List<String> DIRECTIVES = Collections.unmodifiableList(
            [
                    'base-uri',
                    'default-src',
                    'script-src',
                    'object-src',
                    'style-src',
                    'img-src',
                    'media-src',
                    'frame-src',
                    'child-src',
                    'frame-ancestors',
                    'font-src',
                    'connect-src',
                    'manifest-src',
                    'form-action',
                    'sandbox',
                    'script-nonce',
                    'plugin-types',
                    'reflected-xss',
                    'block-all-mixed-content',
                    'upgrade-insecure-requests',
                    'referrer',
                    'report-uri',
                    'report-to',
                    'worker-src'
            ]
    )
}
