#!/bin/sh

set -e

case "$1" in
  configure)
    # If the package has default file it could be sourced, so that
    # the local admin can overwrite the defaults

    [ -f "/etc/default/rundeck" ] && . /etc/default/rundeck
   
    # Sane defaults:
   
    [ -z "$SERVER_HOME" ] && SERVER_HOME=/var/lib/rundeck
    [ -z "$SERVER_USER" ] && SERVER_USER=rundeck
    [ -z "$SERVER_NAME" ] && SERVER_NAME="Rundeck user account"
    [ -z "$SERVER_GROUP" ] && SERVER_GROUP=rundeck
    [ -z "$SERVER_VAR" ] && SERVER_VAR=/var/rundeck
    [ -z "$SERVER_TEMP" ] && SERVER_TEMP=/var/rundeck

    # create user to avoid running server as root
    # 1. create group if not existing
    if ! getent group | grep -q "^$SERVER_GROUP:" ; then
       echo -n "Adding group $SERVER_GROUP.."
       addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
       echo "..done"
    fi
    # 2. create homedir if not existing
    test -d $SERVER_HOME || mkdir $SERVER_HOME
    # 3. create user if not existing
    if ! getent passwd | grep -q "^$SERVER_USER:"; then
      echo -n "Adding system user $SERVER_USER.."
      adduser --quiet \
              --system \
              --ingroup $SERVER_GROUP \
              --no-create-home \
              --disabled-password \
              $SERVER_USER 2>/dev/null || true
      echo "..done"
    fi

    # 4. adjust passwd entry
    usermod -c "$SERVER_NAME" \
            -d $SERVER_HOME   \
            -g $SERVER_GROUP  \
               $SERVER_USER

    # 5. adjust file and directory permissions
    if ! dpkg-statoverride --list $SERVER_HOME >/dev/null
    then
        chown -R $SERVER_USER:adm $SERVER_HOME
        chmod u=rwx,g=rxs,o= $SERVER_HOME
    fi
    if ! dpkg-statoverride --list $SERVER_VAR >/dev/null
    then
        chown -R $SERVER_USER:adm $SERVER_VAR
        chmod u=rwx,g=rxs,o= $SERVER_VAR
    fi
    if ! dpkg-statoverride --list $SERVER_TEMP >/dev/null
    then
        chown -R $SERVER_USER:adm $SERVER_TEMP
        chmod u=rwx,g=rxs,o= $SERVER_TEMP
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    :
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0

