export interface AppLinks {
    [key:string]: string
    api_version: string
    communityNews: string
    project_name: string
    disclosureIcon: string
    disclosureIconOpen: string
    iconTinyWarn: string
    iconTinyOk: string
    iconSmallRemoveX: string
    iconTinyRemoveX: string
    iconSpinner: string
    projectMOTD: string
    executionCancelExecution: string
    executionMarkExecutionIncomplete: string
    tailExecutionOutput: string
    reportsEventsFragment: string
    executionAjaxExecState: string
    executionAjaxExecNodeState: string
    frameworkViewResourceModelConfig: string
    frameworkCheckResourceModelConfig: string
    frameworkEditResourceModelConfig: string
    frameworkCreateResourceModelConfig: string
    frameworkCreateProject: string
    frameworkNodes: string
    frameworkNodesFragment: string
    frameworkNodesQueryAjax: string
    frameworkAdhoc: string
    frameworkReloadNodes: string
    frameworkNodeSummaryAjax: string
    frameworkDeleteNodeFilterAjax: string
    authProjectsToCreateAjax: string
    menuDeleteJobFilterAjax: string
    menuSaveJobFilterAjax: string
    reportsEventsAjax: string
    reportsListFiltersAjax: string
    reportsSaveFilterAjax: string
    reportsDeleteFilterAjax: string
    menuNowrunningAjax: string
    menuHome: string
    menuHomeAjax: string
    menuHomeSummaryAjax: string
    menuProjectNamesAjax: string
    menuJobsAjax: string
    menuJobSearchJson: string
    scheduledExecutionRunAdhocInline: string
    scheduledExecutionCreate: string
    scheduledExecutionExecuteFragment: string
    scheduledExecutionActionMenuFragment: string
    scheduledExecutionRunJobInline: string
    scheduledExecutionScheduleJobInline: string
    scheduledExecutionDetailFragment: string
    scheduledExecutionDetailFragmentAjax: string
    scheduledExecutionJobExecutionsAjax: string
    scheduledExecutionSanitizeHtml: string
    scheduledExecutionWorkflowJson: string
    executionFollowFragment: string
    adhocHistoryAjax: string
    menuJobs: string
    userAddFilterPref: string
    userClearApiToken: string
    userGenerateUserToken: string
    userRevealTokenData: string
    userRenderApiToken: string
    userProfilePage: string

    workflowEdit: string
    workflowCopy: string
    workflowRender: string
    workflowSave: string
    workflowReorder: string
    workflowRemove: string
    workflowUndo: string
    workflowRedo: string
    workflowRevert: string
    workflowRenderUndo: string
    workflowEditStepFilter: string
    workflowSaveStepFilter: string
    workflowValidateStepFilter: string
    workflowRemoveStepFilter: string

    editOptsRenderUndo: string
    editOptsEdit: string
    editOptsRender: string
    editOptsSave: string
    editOptsRenderAll: string
    editOptsRenderSummary: string
    editOptsRemove: string
    editOptsDuplicate: string
    editOptsReorder: string
    editOptsUndo: string
    editOptsRedo: string
    editOptsRevert: string
    menuJobsPicker: string
    scheduledExecutionGroupTreeFragment: string
    storageKeysBrowse: string
    storageKeysApi: string
    storageKeysDownload: string
    storageKeysDelete: string
    apiExecutionsBulkDelete: string

    scmjobs: string
    togglescm: string

    help: string
}