#!/bin/sh
#
# Copyright 2010 DTO Labs, Inc. (http://dtolabs.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# $RCSfile$
# $Revision: 1084 $


errorMsg() {
   echo "$*" 1>&2
}
log () {
        echo ${1}: ${2}
}
#
# This hack checks if this shell script was called within (most probably) a cygwin context
# during an ssh to a windows box and if so, to actually exec the .bat batch file instead.
#
if [ -n "$OS" -a "$OS" = "Windows_NT" ]
then
   exec cmd.exe /C $RDECK_HOME/bin/run-jobs.bat "$@"
fi


if [ "${RDECK_BASE}X" = "X" ]
then
   #determine base
   PDIR=$(cd `dirname $0/`/../.. && pwd)
   if [ -f "$PDIR/etc/framework.properties" ]
   then
       export RDECK_BASE=$PDIR
   fi
fi
if [ "${RDECK_BASE}X" = "X" ]
then
    errorMsg "RDECK_BASE was not set"
    exit 1
fi
if [ ! -r $RDECK_BASE/etc/profile ]; then
   errorMsg "Unable to source $RDECK_BASE/etc/profile"
   exit 1
fi

. $RDECK_BASE/etc/profile


LIBDIR=$RDECK_HOME/tools/lib
cp=
for i in `ls $LIBDIR/*.jar`
do
  cp=${cp}:${i}
done

#
# Launch the cmdline tool
#
exec $JAVA_HOME/bin/java -classpath $cp \
     -Duser.java_home=$JAVA_HOME \
     -Drdeck.base=$RDECK_BASE \
     -Drdeck.home=$RDECK_HOME \
     com.dtolabs.rundeck.core.cli.run.RunTool "$@"
