
Vagrant.configure("2") do |config|

  repo_url = "https://bintray.com/rundeck/ci-snapshot-rpm/rpm"

  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  #config.vm.network :forwarded_port, guest: 4440, host: 14440

  config.vm.synced_folder "../../src", "/rundeck_api_test/src"
  config.vm.synced_folder "../../api", "/rundeck_api_test/api"
  config.vm.synced_folder "../src", "/test_scripts"

  config.vm.provision :shell, :path => "bootstrap.sh", :args => repo_url
  config.vm.provision :shell, :path => "prepare-tests.sh"
  config.vm.provision :shell,
    :inline => "su - rundeck -c 'sh /test_scripts/api-test.sh'"


  config.vm.provider :aws do |aws, override|
    if ENV['AWS_USE_IAM_PROFILE']
      aws.use_iam_profile = true
    else
      aws.access_key_id = ENV['AWS_ACCESS_KEY']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
    end

    aws.keypair_name = ENV['AWS_KEYPAIR_NAME']#"build-ci"

    aws.security_groups =  ENV['AWS_SG_NAME'] #"quicklaunch-1"
    aws.user_data = "#!/bin/bash\necho 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/999-vagrant-cloud-init-requiretty && chmod 440 /etc/sudoers.d/999-vagrant-cloud-init-requiretty\nyum update -y\n"
    #aws.ami = "ami-a6e15bcf" #Centos 6.3 official
    aws.ami = "ami-05355a6c" #Amazon linux amazon/amzn-ami-pv-2013.03.1.x86_64-ebs
    aws.tags = {
      'Name' => 'Rundeck CI Test',
    }

    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = ENV['SSH_KEY_PATH']
  end
end
