// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonUserAvatar: typeof import('~icons/carbon/user-avatar')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Navbar: typeof import('./core/components/Navbar.vue')['default']
    README: typeof import('./core/components/README.md')['default']
    TheFooter: typeof import('./core/components/TheFooter.vue')['default']
  }
}

export { }
