name: Test

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.19.0, 16.14.0]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Static Analysis
        run: pnpm lint

      - name: Build Static Distribution
        run: pnpm build:prod:ssg

      # Need to test with SPA distribution due to Cypress flakiness ¯\_(ツ)_/¯
      - name: Build SPA Distribution
        run: |
          pnpm prebuild \
            && pnpm build:prod:spa

      - name: Cypress Component Test Runner
        run: pnpm test:components:ci

      - name: Cypress End-to-End Test Runner
        run: pnpm test:e2e:ci
