
Vagrant.configure("2") do |config|

  repo_url = "https://bintray.com/rundeck/ci-snapshot-rpm/rpm"
  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  config.vm.network :forwarded_port, guest: 4440, host: 14440

  config.vm.synced_folder "../../src", "/rundeck_api_test/src"
  config.vm.synced_folder "../../api", "/rundeck_api_test/api"
  config.vm.synced_folder "../src", "/test_scripts"

  config.vm.provision :shell, :path => "bootstrap.sh", :args => repo_url
  config.vm.provision :shell, :path => "prepare-tests.sh"
  config.vm.provision :shell,
    :inline => "su - rundeck -c 'sh /test_scripts/api-test.sh'"

end
