/*
 * Copyright 2024 Rundeck, Inc. (http://rundeck.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.rundeck.jaas

import org.apache.commons.codec.digest.UnixCrypt
import org.eclipse.jetty.util.security.Password
import org.springframework.security.crypto.bcrypt.BCrypt
import spock.lang.Specification

class PasswordCredentialSpec extends Specification {

    def "plain text password matches"() {
        given:
        def credential = PasswordCredential.getCredential("mypassword")

        expect:
        credential.check("mypassword")
        !credential.check("wrongpassword")
    }

    def "MD5 hex format password matches"() {
        given:
        def password = "testpassword"
        def md5Hex = PasswordCredential.md5Digest(password)
        def credential = PasswordCredential.getCredential("MD5:${md5Hex}")

        expect:
        credential.check(password)
        !credential.check("wrongpassword")
    }

    def "BCRYPT password matches"() {
        given:
        def password = "securePassword123"
        def hash = BCrypt.hashpw(password, BCrypt.gensalt())
        def credential = PasswordCredential.getCredential("BCRYPT:${hash}")

        expect:
        credential.check(password)
        !credential.check("wrongPassword")
    }

    def "BCRYPT password works with char array input"() {
        given:
        def password = "securePassword123"
        def hash = BCrypt.hashpw(password, BCrypt.gensalt())
        def credential = PasswordCredential.getCredential("BCRYPT:${hash}")

        expect:
        credential.check(password.toCharArray())
        !credential.check("wrong".toCharArray())
    }

    def "BCRYPT invalid hash returns false instead of exception"() {
        given:
        def credential = PasswordCredential.getCredential("BCRYPT:not-a-valid-hash")

        expect:
        !credential.check("anypassword")
    }

    def "CRYPT password matches with Unix DES crypt"() {
        given:
        def password = "pepe2"
        def cryptHash = UnixCrypt.crypt(password, "pe")
        def credential = PasswordCredential.getCredential("CRYPT:${cryptHash}")

        expect:
        credential.check(password)
        !credential.check("wrongpassword")
    }

    def "CRYPT password matches known Jetty-generated hash"() {
        given: "a hash generated by Jetty Credential.Crypt in Rundeck 5.x"
        def credential = PasswordCredential.getCredential("CRYPT:peKgBO9s0.gUQ")

        expect:
        credential.check("pepe2")
        !credential.check("wrong")
    }

    def "OBF password matches known Jetty-generated obfuscation"() {
        given: "an OBF value generated by Jetty Password.obfuscate in Rundeck 5.x"
        def credential = PasswordCredential.getCredential("OBF:1l8d1t331xfj1t331l4x")

        expect:
        credential.check("pepe2")
        !credential.check("wrongpassword")
    }

    def "OBF credential with dynamically obfuscated password matches"() {
        given:
        def password = "testPassword123"
        def obfuscated = Password.obfuscate(password)
        def credential = PasswordCredential.getCredential(obfuscated)

        expect:
        credential.check(password)
        !credential.check("wrong")
    }

    def "null password credential checks correctly"() {
        given:
        def credential = PasswordCredential.getCredential(null)

        expect:
        credential.check(null)
        !credential.check("something")
    }

    def "null input to check returns false for non-null credential"() {
        given:
        def credential = PasswordCredential.getCredential("somepassword")

        expect:
        !credential.check(null)
    }

}
