
Vagrant.configure("2") do |config|

  config.vm.box = "CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"

  config.vm.network :forwarded_port, guest: 4440, host: 14440

  config.vm.synced_folder "../../", "/rundeck_api_test"
  config.vm.synced_folder "../src", "/test_scripts"

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "prepare-tests.sh"
  config.vm.provision :shell,
    :inline => "su - rundeck -c 'sh /test_scripts/api-test.sh'"

end
